### ISSUE TITLE
Consistent env for database creds

### ISSUE THREAD

**Issue by rithvikvibhu** [bluesky-social/did-method-plc#15]
PDS uses `PG_DATABASE_URL` as a connection string. This PLC server uses a stringified json object from `DB_CREDS_JSON`. It'd be nice to use the same `PG_DATABASE_URL` everywhere, and personally, connection strings are better - simple, short, and standard.

**Comment by bnewbold** [comment]
These are now at least consistent, both `DB_CREDS_JSON`.
