### ISSUE TITLE
Add did:plc to the DID Method Registry

### ISSUE THREAD

**Issue by nickreynolds** [bluesky-social/did-method-plc#19]
I've written a "did:plc driver" for the Universal Resolver, but it can't be added until this DID Method is on the Registry. 

Instructions for registering a new DID method are here: https://github.com/w3c/did-spec-registries#adding-a-did-method-to-this-registry

For obvious reasons, it's best if that PR is created by one the primary maintainers of this method.

Based on some feedback I received from one of the registry maintainers, it's likely that the registration would be accepted with the spec in its current state. There's some debate about how defined a DID Method spec should be before it is accepted, but the reality is that there are many "in progress" DID Methods registered. And considering that `did:plc` is currently being used by tens of thousands of people in a fairly public setting, I definitely think it'd be in the public interest to have it registered soon.

If you'd like, I could also try to submit a PR to this repo to slightly reformat the spec to more closely align with how most other DID Methods are specified. There's no requirement for this format, it just might be a bit easier for people to read.

**Comment by dholms** [comment]
Sweet thanks for doing the search on this & getting some resources together!

Unfortunately we did a refactor of PLC about a month ago & the README is not up to date (pretty sizable differences in the data model). It's a near term priority! As soon as we get the chance to update the documentation, we'll submit it to the registry

**Comment by OR13** [comment]
I started this PR to help push this along, if this is something you want to do: https://github.com/bluesky-social/did-method-plc/pull/21

**Comment by nickreynolds** [comment]
looks like I spoke too soon on the formatting issues 😅

**Comment by bnewbold** [comment]
Just to cross-reference, opened a PR last week over in the W3C DID method registry to add did:plc: https://github.com/w3c/did-spec-registries/pull/515
