### ISSUE TITLE
lock-down did:plc identifier length to 24 chars

### ISSUE THREAD

**Issue by bnewbold** [bluesky-social/did-method-plc#27]
The currently implementation is flexible in a couple places, and will do prefix matching instead of direct string comparison. While it is kind of nice to be flexible to longer DIDs (more hash-collision-resistant?), it feels like from a belt-and-suspenders perspective we should lock things down to a deterministic length.

I'm a little worried specifically about re-registering existing `create` ops as new DIDs with the same prefix, though I haven't verified if that is actually possible. The inverse might also be possible (re-register with shorter DID if a longer one was used first).

**Comment by dholms** [comment]
The intention actually was to allow flexibility for longer DIDs for collision resistance. But we're not using it anywhere & I'm not sure that we've thought through all the possible implications of that (as you point out).

I'd be down to lockdown to 24 chars for now, with the option to become more liberal over time

**Comment by DavidBuchanan314** [comment]
It is indeed possible to re-register existing DIDs with the same prefix:

https://plc.directory/did:plc:vwzwgnygau7ed7b7wt5ux7y2

https://plc.directory/did:plc:vwzwgnygau7ed7b7wt5ux7y2dgymw73fad3n6bxlkzuw6lyyq2sq
